"use client";

import { useEffect, useMemo, useState } from "react";

type Mission = { id: string; title: string; service: string } & Record<string, unknown>;
type EventType = "MISSION_CREATED" | "FIELD_UPDATED" | "POLICY_DECIDED" | "APPROVAL_RECORDED" | "ROUTE_OPENED" | "VERIFICATION_RECORDED" | "ROLLBACK_RECORDED" | "MISSION_CLOSED";
type ChainEvent = { id:string; missionId:string; type:EventType; occurredAt:string; actor:string; data:Record<string,unknown>; previousDigest:string|null; digest:string };

const MISSION_KEY="jp-hviti-service-bridge-v2";
const EVENT_KEY="jp-hviti-service-bridge-events-v1";
const eventTypes:EventType[]=["MISSION_CREATED","FIELD_UPDATED","POLICY_DECIDED","APPROVAL_RECORDED","ROUTE_OPENED","VERIFICATION_RECORDED","ROLLBACK_RECORDED","MISSION_CLOSED"];

export default function EventChainPage(){
 const [missions,setMissions]=useState<Mission[]>([]);const [events,setEvents]=useState<ChainEvent[]>([]);const [missionId,setMissionId]=useState("");const [type,setType]=useState<EventType>("MISSION_CREATED");const [actor,setActor]=useState("JP");const [dataText,setDataText]=useState("{}");const [verification,setVerification]=useState<Record<string,unknown>|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{try{const m=localStorage.getItem(MISSION_KEY),e=localStorage.getItem(EVENT_KEY);if(m){const parsed=JSON.parse(m);setMissions(parsed);if(parsed[0])setMissionId(parsed[0].id)}if(e)setEvents(JSON.parse(e));}catch{setError("Could not load local mission or event data.")}},[]);
 useEffect(()=>{localStorage.setItem(EVENT_KEY,JSON.stringify(events));},[events]);
 const mission=useMemo(()=>missions.find(m=>m.id===missionId)||null,[missions,missionId]);
 async function append(){setLoading(true);setError("");setVerification(null);try{const data=JSON.parse(dataText);const previousEvent=events.at(-1)||null;const response=await fetch("/api/service-bridge/events/append",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId,type,actor,data,previousEvent})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Event append failed.");setEvents(current=>[...current,body.event]);setDataText("{}");}catch(cause){setError(cause instanceof Error?cause.message:"Event append failed.");}finally{setLoading(false)}}
 async function verify(){setLoading(true);setError("");try{const response=await fetch("/api/service-bridge/events/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({events})});const body=await response.json();setVerification(body);if(!response.ok&&response.status!==422)throw new Error(body.error||"Verification failed.");}catch(cause){setError(cause instanceof Error?cause.message:"Verification failed.");}finally{setLoading(false)}}
 function exportChain(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),events},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="jp-hviti-event-chain.json";a.click();URL.revokeObjectURL(a.href)}
 return <main className="min-h-screen bg-[#07070b] text-[#f5efe2]"><section className="mx-auto w-full max-w-7xl px-6 py-10 sm:px-10 lg:px-12">
  <nav className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-5 text-sm text-white/60"><a className="font-mono uppercase tracking-[.3em] text-cyan-200" href="/service-bridge">Service Bridge</a><div className="flex gap-3"><a href="/service-bridge/control">Control</a><a href="/service-bridge/receipts">Receipts</a><a href="/service-bridge/status">Status</a></div></nav>
  <header className="grid gap-8 py-16 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="mb-4 inline-flex rounded-full border border-fuchsia-300/30 bg-fuchsia-300/10 px-4 py-2 text-sm text-fuchsia-100">Ordered mission history • local event chain</p><h1 className="text-5xl font-black sm:text-7xl">Event Chain</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Append mission events, preserve previous-digest links, verify event order and content, and export the complete local chain.</p></div><div className="rounded-[2rem] border border-amber-300/25 bg-amber-300/[.08] p-6"><p className="font-semibold text-amber-100">Integrity boundary</p><p className="mt-3 text-sm leading-6 text-white/60">This detects local content or ordering changes. It is not a signature, blockchain, notarization, trusted timestamp, identity proof, or proof that an external action happened.</p></div></header>
  <section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]">
   <aside className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black">Append event</h2><div className="mt-5 space-y-4"><select className="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3" value={missionId} onChange={e=>setMissionId(e.target.value)}><option value="">Select mission</option>{missions.map(m=><option key={m.id} value={m.id}>{m.title} — {m.service}</option>)}</select><select className="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3" value={type} onChange={e=>setType(e.target.value as EventType)}>{eventTypes.map(t=><option key={t}>{t}</option>)}</select><input className="w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3" value={actor} onChange={e=>setActor(e.target.value)} placeholder="Actor"/><textarea className="min-h-44 w-full rounded-2xl border border-white/10 bg-black/30 p-4 font-mono text-sm" value={dataText} onChange={e=>setDataText(e.target.value)} placeholder='{"field":"value"}'/></div><button onClick={append} disabled={!missionId||loading} className="mt-5 rounded-full bg-cyan-200 px-5 py-3 font-bold text-black disabled:opacity-40">{loading?"Working…":"Append event"}</button>{mission?<pre className="mt-5 overflow-x-auto rounded-2xl bg-black/30 p-4 text-xs text-cyan-100">{JSON.stringify(mission,null,2)}</pre>:null}</aside>
   <section className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">Chain timeline</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-white/60">{events.length} events</span></div><div className="mt-5 space-y-4">{events.length===0?<div className="rounded-3xl border border-dashed border-white/15 p-8 text-center text-white/45">No events recorded.</div>:events.map((event,index)=><article key={event.id} className="rounded-3xl border border-white/10 bg-black/20 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-fuchsia-200/70">#{index+1} {event.type}</p><h3 className="mt-1 font-bold">{event.missionId}</h3><p className="mt-1 text-sm text-white/50">{event.actor} • {event.occurredAt}</p></div><span className="max-w-xs break-all rounded-2xl bg-cyan-200/10 px-3 py-2 font-mono text-xs text-cyan-100">{event.digest}</span></div><pre className="mt-4 overflow-x-auto rounded-2xl bg-black/30 p-4 text-xs leading-5 text-white/65">{JSON.stringify(event.data,null,2)}</pre><p className="mt-3 break-all text-xs text-white/40">Previous: {event.previousDigest||"GENESIS"}</p></article>)}</div></section>
  </section>
  {error?<div className="mt-6 rounded-2xl border border-red-300/30 bg-red-300/10 p-4 text-red-100">{error}</div>:null}
  <section className="mt-8 flex flex-wrap gap-3"><button onClick={verify} disabled={!events.length||loading} className="rounded-full border border-cyan-200/30 px-5 py-3 font-bold text-cyan-100 disabled:opacity-40">Verify chain</button><button onClick={exportChain} disabled={!events.length} className="rounded-full border border-white/15 px-5 py-3 font-bold disabled:opacity-40">Export chain</button><button onClick={()=>{if(confirm("Clear the locally stored event chain?")){setEvents([]);setVerification(null)}}} className="rounded-full border border-red-300/20 px-5 py-3 font-bold text-red-200">Clear local chain</button></section>
  <section className="mt-8 rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-black">Verification result</h2><pre className="mt-5 overflow-x-auto rounded-2xl bg-black/30 p-4 text-sm leading-6 text-cyan-100">{verification?JSON.stringify(verification,null,2):"No chain verification run yet."}</pre></section>
 </section></main>
}
