import { NextResponse } from "next/server";

const jsonBody = (schema: Record<string, unknown>) => ({ required: true, content: { "application/json": { schema } } });

export function GET() {
  return NextResponse.json({
    openapi: "3.1.0",
    info: {
      title: "JP / Hviti Service Bridge API",
      version: "16.0.0",
      description: "Local-first orchestration, reversible recovery, mission-scoped lifecycle journaling, derived lifecycle projection, and explicitly confirmed local projection application.",
    },
    servers: [{ url: "/" }],
    paths: {
      "/api/service-bridge/manifest": { get: { summary: "Read the manifest", responses: { "200": { description: "Manifest" } } } },
      "/api/service-bridge/health": { get: { summary: "Read health", responses: { "200": { description: "Healthy" }, "503": { description: "Degraded" } } } },
      "/api/service-bridge/validate": { post: { summary: "Validate one mission", requestBody: jsonBody({ $ref: "#/components/schemas/Mission" }), responses: { "200": { description: "Validation" } } } },
      "/api/service-bridge/validate-batch": { post: { summary: "Validate mission batch", requestBody: jsonBody({ $ref: "#/components/schemas/MissionBatch" }), responses: { "200": { description: "Batch validation" }, "413": { description: "Too large" } } } },
      "/api/service-bridge/policy/evaluate": { post: { summary: "Evaluate policy", requestBody: jsonBody({ $ref: "#/components/schemas/Mission" }), responses: { "200": { description: "Policy decision" } } } },
      "/api/service-bridge/orchestrate": { post: { summary: "Orchestrate one mission", requestBody: jsonBody({ $ref: "#/components/schemas/Mission" }), responses: { "200": { description: "Orchestration" }, "422": { description: "Incomplete" } } } },
      "/api/service-bridge/orchestrate-batch": { post: { summary: "Orchestrate mission batch", requestBody: jsonBody({ $ref: "#/components/schemas/MissionBatch" }), responses: { "200": { description: "Batch orchestration" }, "413": { description: "Too large" } } } },
      "/api/service-bridge/plan": { post: { summary: "Generate route plan", requestBody: jsonBody({ $ref: "#/components/schemas/Mission" }), responses: { "200": { description: "Plan" }, "422": { description: "Incomplete" } } } },
      "/api/service-bridge/queue": { post: { summary: "Prioritize queue", requestBody: jsonBody({ $ref: "#/components/schemas/MissionQueue" }), responses: { "200": { description: "Queue" }, "413": { description: "Too large" } } } },
      "/api/service-bridge/receipt": { get: { summary: "Read system receipt", responses: { "200": { description: "Receipt" } } } },
      "/api/service-bridge/receipt/mission": { post: { summary: "Create mission receipt", requestBody: jsonBody({ $ref: "#/components/schemas/Mission" }), responses: { "200": { description: "Receipt" }, "422": { description: "Incomplete" } } } },
      "/api/service-bridge/receipt/verify": { post: { summary: "Verify receipt", requestBody: jsonBody({ $ref: "#/components/schemas/MissionReceipt" }), responses: { "200": { description: "Valid" }, "422": { description: "Mismatch" } } } },
      "/api/service-bridge/events/append": { post: { summary: "Append event", requestBody: jsonBody({ $ref: "#/components/schemas/EventAppendRequest" }), responses: { "200": { description: "Event" } } } },
      "/api/service-bridge/events/verify": { post: { summary: "Verify event chain", requestBody: jsonBody({ $ref: "#/components/schemas/EventChain" }), responses: { "200": { description: "Valid" }, "422": { description: "Broken" } } } },
      "/api/service-bridge/events/project": { post: { summary: "Project mission state from event chain", requestBody: jsonBody({ $ref: "#/components/schemas/EventChain" }), responses: { "200": { description: "Projection" }, "422": { description: "Invalid chain" } } } },
      "/api/service-bridge/events/reconcile": { post: { summary: "Reconcile snapshot with projected history", requestBody: jsonBody({ $ref: "#/components/schemas/ReconciliationRequest" }), responses: { "200": { description: "Consistent" }, "409": { description: "Conflict" } } } },
      "/api/service-bridge/events/resolve": { post: { summary: "Create an explicit authority resolution packet", requestBody: jsonBody({ $ref: "#/components/schemas/ResolutionRequest" }), responses: { "200": { description: "Resolution packet" }, "400": { description: "Invalid authority or missing reason" } } } },
      "/api/service-bridge/events/persist": { post: { summary: "Create a gated local persistence plan", requestBody: jsonBody({ $ref: "#/components/schemas/PersistenceRequest" }), responses: { "200": { description: "Persistence plan" }, "400": { description: "Invalid resolution or confirmation" } } } },
      "/api/service-bridge/events/rollback": { post: { summary: "Create a gated local rollback plan", requestBody: jsonBody({ $ref: "#/components/schemas/RollbackRequest" }), responses: { "200": { description: "Rollback plan" }, "400": { description: "Invalid receipt or confirmation" } } } },
      "/api/service-bridge/lifecycle": { post: { summary: "Append or verify a mission lifecycle journal", requestBody: jsonBody({ oneOf: [{ $ref: "#/components/schemas/LifecycleAppendRequest" }, { $ref: "#/components/schemas/LifecycleVerifyRequest" }] }), responses: { "200": { description: "Entry or valid verification" }, "400": { description: "Invalid payload" }, "422": { description: "Broken lifecycle journal" } } } },
      "/api/service-bridge/lifecycle/project": { post: { summary: "Project derived lifecycle state from a journal", requestBody: jsonBody({ $ref: "#/components/schemas/LifecycleProjectionRequest" }), responses: { "200": { description: "Valid lifecycle projection" }, "400": { description: "Invalid payload" }, "422": { description: "Invalid lifecycle chain with diagnostic projection" } } } },
      "/api/service-bridge/lifecycle/apply": { post: { summary: "Create an explicitly confirmed local lifecycle projection apply plan", requestBody: jsonBody({ $ref: "#/components/schemas/LifecycleApplyRequest" }), responses: { "200": { description: "Projection apply plan" }, "400": { description: "Invalid projection, mission, or confirmation" } } } },
      "/api/service-bridge/openapi": { get: { summary: "Read this document", responses: { "200": { description: "OpenAPI" } } } },
    },
    components: { schemas: {
      Mission: { type: "object", required: ["id", "title", "service", "target", "action", "owner", "state", "priority", "permission", "evidence", "fallback"], properties: { id: { type: "string" }, state: { enum: ["draft", "preflight", "awaiting-approval", "ready", "verified", "closed"] } } },
      MissionBatch: { type: "object", required: ["missions"], properties: { missions: { type: "array", items: { $ref: "#/components/schemas/Mission" } } } },
      MissionQueue: { type: "object", required: ["missions"], properties: { missions: { type: "array", items: { $ref: "#/components/schemas/Mission" } } } },
      MissionReceipt: { type: "object" },
      ChainEvent: { type: "object", required: ["id", "missionId", "type", "occurredAt", "actor", "data", "previousDigest", "digest"] },
      EventAppendRequest: { type: "object", required: ["missionId", "type", "actor"] },
      EventChain: { type: "object", required: ["events"], properties: { events: { type: "array", items: { $ref: "#/components/schemas/ChainEvent" } } } },
      ReconciliationRequest: { type: "object", required: ["snapshot", "events"] },
      ResolutionRequest: { type: "object", required: ["snapshot", "events", "authority", "actor", "reason"] },
      ResolutionPacket: { type: "object", required: ["schema", "missionId", "authority", "resolvedState", "mutationApplied", "requiresExplicitPersistence", "externalActionCompleted"] },
      PersistenceRequest: { type: "object", required: ["resolution", "currentMissions", "confirmation"] },
      LocalPersistenceReceipt: { type: "object", required: ["schema", "missionId", "storageKey", "previousMission", "nextMission", "localMutationApplied", "externalPersistenceApplied", "externalActionCompleted"] },
      RollbackRequest: { type: "object", required: ["receipt", "currentMissions", "confirmation"] },
      LifecycleEntry: { type: "object", required: ["schema", "id", "missionId", "type", "recordedAt", "actor", "data", "previousDigest", "digest", "externalActionCompleted"], properties: { schema: { const: "jp-hviti-service-bridge-lifecycle-entry/v1" }, type: { enum: ["RESOLUTION_CREATED", "PERSISTENCE_PLANNED", "LOCAL_PERSISTENCE_APPLIED", "ROLLBACK_PLANNED", "LOCAL_ROLLBACK_APPLIED"] }, previousDigest: { type: ["string", "null"] }, digest: { type: "string" }, externalActionCompleted: { const: false } } },
      LifecycleAppendRequest: { type: "object", required: ["operation", "missionId", "type", "actor", "data"], properties: { operation: { const: "append" }, previousEntry: { oneOf: [{ $ref: "#/components/schemas/LifecycleEntry" }, { type: "null" }] } } },
      LifecycleVerifyRequest: { type: "object", required: ["operation", "entries"], properties: { operation: { const: "verify" }, entries: { type: "array", items: { $ref: "#/components/schemas/LifecycleEntry" } } } },
      LifecycleProjectionRequest: { type: "object", required: ["entries"], properties: { entries: { type: "array", items: { $ref: "#/components/schemas/LifecycleEntry" } } } },
      LifecycleProjection: { type: "object", required: ["schema", "missionId", "journalValid", "state", "externalActionCompleted"], properties: { schema: { const: "jp-hviti-service-bridge-lifecycle-projection/v1" }, journalValid: { type: "boolean" }, state: { type: "object", required: ["persisted", "rolledBack", "unresolvedPlan"] }, externalActionCompleted: { const: false } } },
      LifecycleApplyRequest: { type: "object", required: ["projection", "currentMissions", "projectedMission", "confirmation"], properties: { projection: { $ref: "#/components/schemas/LifecycleProjection" }, currentMissions: { type: "array", items: { $ref: "#/components/schemas/Mission" } }, projectedMission: { $ref: "#/components/schemas/Mission" }, confirmation: { type: "string", pattern: "^APPLY PROJECTION .+" } } },
      LifecycleApplyPlan: { type: "object", required: ["schema", "missionId", "previousMission", "nextMission", "nextMissions", "projectionMutationAllowed", "projectionMutationApplied", "explicitConfirmationRequired", "localPersistenceAllowed", "externalPersistenceAllowed", "externalActionCompleted"], properties: { schema: { const: "jp-hviti-service-bridge-lifecycle-projection-apply-plan/v1" }, projectionMutationAllowed: { const: true }, projectionMutationApplied: { const: false }, explicitConfirmationRequired: { const: true }, localPersistenceAllowed: { const: true }, externalPersistenceAllowed: { const: false }, externalActionCompleted: { const: false } } },
    } },
    "x-jp-hviti-approval-law": { externalActionsRequireExplicitApproval: true, externalActionCompletedByApi: false },
    "x-recovery-stages": ["event-chain", "verify", "project", "reconcile", "resolve-authority", "plan-persistence", "explicit-local-write", "plan-rollback", "explicit-local-restore", "append-lifecycle-entry", "verify-lifecycle-journal", "project-lifecycle", "plan-projection-apply", "explicit-projection-commit"],
    "x-lifecycle-journal": { missionScoped: true, orderedByPreviousDigest: true, digestAlgorithm: "SHA-256", canonicalization: "sorted-json-v1", trustedTimestamp: false, signed: false, notarized: false, blockchain: false, externalActionProof: false },
    "x-lifecycle-projection": { readOnly: true, invalidJournalStatus: 422, derivesPersistedState: true, derivesRollbackState: true, detectsUnresolvedPlans: true },
    "x-lifecycle-projection-apply": { explicitLocalMutationAllowed: true, automaticMutationAllowed: false, planningConfirmationPattern: "APPLY PROJECTION <mission-id>", commitConfirmationPattern: "COMMIT PROJECTION <mission-id>", externalPersistenceAllowed: false },
    "x-silent-overwrite-allowed": false,
    "x-automatic-mutation-allowed": false,
    "x-automatic-rollback-allowed": false,
    "x-external-persistence-allowed": false,
    "x-external-rollback-allowed": false,
  });
}
