"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type MissionState = "draft" | "preflight" | "awaiting-approval" | "ready" | "verified" | "closed";
type Mission = { id:string; title:string; service:string; target:string; action:string; owner:string; state:MissionState; priority:number; budget:string; permission:string; evidence:string; fallback:string; next:string; query:string; location:string; updatedAt:string };
type Service = { name:string; kind:string; capability:string; href:string };

const STORAGE_KEY="jp-hviti-service-bridge-v2";
const states:MissionState[]=["draft","preflight","awaiting-approval","ready","verified","closed"];
const services:Service[]=[
{name:"Indeed",kind:"Public launcher",capability:"Job search and application preparation",href:"https://www.indeed.com/"},
{name:"Uber",kind:"Public launcher",capability:"Ride planning and mobility",href:"https://www.uber.com/"},
{name:"Grubhub",kind:"Public launcher",capability:"Food search and delivery planning",href:"https://www.grubhub.com/"},
{name:"LinkedIn",kind:"Public launcher",capability:"Professional and job search",href:"https://www.linkedin.com/jobs/"},
{name:"Gmail",kind:"Connected tool",capability:"Drafting, review, and explicit send",href:"https://mail.google.com/"},
{name:"Google Calendar",kind:"Connected tool",capability:"Scheduling and event control",href:"https://calendar.google.com/"},
{name:"GitHub",kind:"Connected tool",capability:"Code, versions, issues, and receipts",href:"https://github.com/hvitiswift-afk/nextjs-boilerplate"},
{name:"Expedia",kind:"Public launcher",capability:"Travel and lodging research",href:"https://www.expedia.com/"},
{name:"Norstein",kind:"JP / Hviti route",capability:"Preview, testing, and supporter workflow",href:"/norstein-preview/index.html"},
{name:"V# MAIN",kind:"JP / Hviti route",capability:"Direct visual-work preparation",href:"/jp-hviti-work-nexus/index.html"},
];
const blankMission:Mission={id:"",title:"",service:"Indeed",target:"",action:"",owner:"JP",state:"draft",priority:5,budget:"",permission:"",evidence:"",fallback:"Manual copy / alternate service",next:"",query:"",location:"",updatedAt:""};
const readiness=(m:Mission)=>Math.round(([m.title,m.target,m.action,m.owner,m.permission,m.evidence,m.fallback].filter(x=>x.trim()).length/7)*100);
function launchUrl(m:Mission){const q=encodeURIComponent(m.query||m.target),l=encodeURIComponent(m.location);if(m.service==="Indeed")return `https://www.indeed.com/jobs?q=${q}&l=${l}`;if(m.service==="LinkedIn")return `https://www.linkedin.com/jobs/search/?keywords=${q}&location=${l}`;if(m.service==="Grubhub")return `https://www.grubhub.com/search?queryText=${q}`;if(m.service==="GitHub")return `https://github.com/search?q=${q}&type=repositories`;return services.find(s=>s.name===m.service)?.href||"#"}

export default function ServiceBridgePage(){
 const [missions,setMissions]=useState<Mission[]>([]); const [draft,setDraft]=useState<Mission>(blankMission); const [selectedId,setSelectedId]=useState<string|null>(null); const [filter,setFilter]=useState("all"); const [search,setSearch]=useState(""); const [hydrated,setHydrated]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setMissions(JSON.parse(raw));}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(STORAGE_KEY,JSON.stringify(missions));},[missions,hydrated]);
 const ordered=useMemo(()=>missions.filter(m=>(filter==="all"||m.state===filter)&&`${m.title} ${m.service} ${m.target}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.priority-a.priority||readiness(b)-readiness(a)),[missions,filter,search]);
 const selected=missions.find(m=>m.id===selectedId)||null;
 function saveMission(){const m={...draft,id:draft.id||`XYZ-${Date.now()}`,title:draft.title||"Untitled XYZ mission",updatedAt:new Date().toISOString()};setMissions(cur=>cur.some(x=>x.id===m.id)?cur.map(x=>x.id===m.id?m:x):[...cur,m]);setSelectedId(m.id);setDraft(blankMission)}
 function advance(id:string){setMissions(cur=>cur.map(m=>{if(m.id!==id)return m;const next=states[Math.min(states.indexOf(m.state)+1,states.length-1)];return{...m,state:next,updatedAt:new Date().toISOString()}}))}
 function exportData(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),missions},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="jp-hviti-service-bridge.json";a.click();URL.revokeObjectURL(a.href)}
 function importData(file:File){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));setMissions(Array.isArray(data)?data:(data.missions||[]))}catch{alert("Invalid Service Bridge JSON")}};reader.readAsText(file)}
 return <main className="min-h-screen bg-[#07070b] text-[#f5efe2]"><section className="mx-auto w-full max-w-7xl px-6 py-10 sm:px-10 lg:px-12">
  <nav className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-5 text-sm text-white/60"><a className="font-mono uppercase tracking-[.3em] text-cyan-200" href="/">JP / Hviti</a><div className="flex gap-3"><a href="/vault">Vault</a><a href="/griploom">GRIPLOOM</a><a href="/f-wad">F-WAD</a></div></nav>
  <header className="grid gap-10 py-16 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="mb-4 inline-flex rounded-full border border-fuchsia-300/30 bg-fuchsia-300/10 px-4 py-2 text-sm text-fuchsia-100">Persistent XYZ mission control • local-first</p><h1 className="text-5xl font-black sm:text-7xl">Service Bridge</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">A consolidated Next.js command surface for mission queues, service routing, readiness, approval gates, receipts, filters, export, import, and carry-forward continuity.</p></div><div className="rounded-[2rem] border border-cyan-200/20 bg-cyan-200/[.06] p-6"><p className="font-semibold text-cyan-100">Execution law</p><p className="mt-3 text-sm leading-6 text-white/60">Preparation may be fast. Purchases, bookings, orders, applications, payments, submissions, and sends remain behind explicit user approval.</p></div></header>
  <section className="grid gap-6 lg:grid-cols-[.95fr_1.05fr]">
   <form className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6" onSubmit={e=>{e.preventDefault();saveMission()}}><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-black">XYZ mission editor</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs">Review Door</span></div><div className="grid gap-4 sm:grid-cols-2">
    <input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3" placeholder="Mission title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><select className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3" value={draft.service} onChange={e=>setDraft({...draft,service:e.target.value})}>{services.map(s=><option key={s.name}>{s.name}</option>)}</select>
    {(["target","action","owner","budget","permission","evidence","fallback","next","query","location"] as const).map(k=><input key={k} className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3" placeholder={k[0].toUpperCase()+k.slice(1)} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>)}
    <label className="sm:col-span-2"><span className="mb-2 block text-sm text-white/60">Priority: {draft.priority}</span><input className="w-full" type="range" min="1" max="10" value={draft.priority} onChange={e=>setDraft({...draft,priority:Number(e.target.value)})}/></label>
   </div><div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-cyan-200 px-5 py-3 font-bold text-black">Save mission</button><button type="button" className="rounded-full border border-white/15 px-5 py-3 font-bold" onClick={()=>setDraft(blankMission)}>Clear</button></div></form>
   <section className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">Mission queue</h2><span className="rounded-full bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200">{missions.length} stored</span></div><div className="mb-5 grid gap-3 sm:grid-cols-2"><input className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3" placeholder="Search missions" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All states</option>{states.map(s=><option key={s}>{s}</option>)}</select></div><div className="space-y-4">{ordered.length===0?<div className="rounded-3xl border border-dashed border-white/15 p-8 text-center text-white/45">No matching missions.</div>:ordered.map(m=><article key={m.id} className="rounded-3xl border border-white/10 bg-black/20 p-5"><div className="flex justify-between gap-3"><div><h3 className="text-lg font-bold">{m.title}</h3><p className="text-sm text-white/50">{m.service} • {m.state} • priority {m.priority}</p></div><span className="rounded-full bg-cyan-200/10 px-3 py-1 text-sm text-cyan-100">{readiness(m)}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-cyan-300 via-violet-300 to-fuchsia-300" style={{width:`${readiness(m)}%`}}/></div><p className="mt-4 text-sm text-white/60"><strong>Target:</strong> {m.target||"Not set"}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>{setDraft(m);setSelectedId(m.id)}} className="rounded-full border border-white/15 px-4 py-2 text-sm">Open</button><button onClick={()=>advance(m.id)} className="rounded-full border border-cyan-200/30 px-4 py-2 text-sm text-cyan-100">Advance</button><a href={launchUrl(m)} target="_blank" rel="noopener noreferrer" className="rounded-full border border-fuchsia-200/30 px-4 py-2 text-sm text-fuchsia-100">Launch route</a><button onClick={()=>setMissions(cur=>cur.filter(x=>x.id!==m.id))} className="rounded-full border border-red-300/20 px-4 py-2 text-sm text-red-200">Remove</button></div></article>)}</div></section>
  </section>
  <section className="mt-10 flex flex-wrap gap-3 border-t border-white/10 py-10"><button onClick={exportData} className="rounded-full border border-cyan-200/30 px-5 py-3 font-bold text-cyan-100">Export JSON</button><button onClick={()=>fileRef.current?.click()} className="rounded-full border border-white/15 px-5 py-3 font-bold">Import JSON</button><input ref={fileRef} className="hidden" type="file" accept="application/json" onChange={e=>{const f=e.target.files?.[0];if(f)importData(f)}}/><button onClick={()=>{if(confirm("Clear all locally stored Service Bridge missions?"))setMissions([])}} className="rounded-full border border-red-300/20 px-5 py-3 font-bold text-red-200">Clear local data</button></section>
  <section className="border-t border-white/10 py-12"><h2 className="text-3xl font-black">Service registry</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{services.map(s=><a key={s.name} href={s.href} target={s.href.startsWith("http")?"_blank":undefined} rel={s.href.startsWith("http")?"noopener noreferrer":undefined} className="rounded-3xl border border-white/10 bg-white/[.035] p-5 hover:border-cyan-200/40"><span className="text-lg font-bold text-cyan-100">{s.name}</span><span className="mt-2 block text-xs uppercase tracking-wider text-fuchsia-200/70">{s.kind}</span><span className="mt-3 block text-sm text-white/55">{s.capability}</span></a>)}</div></section>
  <section className="grid gap-6 border-t border-white/10 py-12 lg:grid-cols-3"><div><h2 className="text-3xl font-black">Selected receipt</h2><p className="mt-3 text-white/60">Truthful current state; no external action implied.</p></div><pre className="overflow-x-auto rounded-[2rem] border border-white/10 bg-black/30 p-6 text-sm text-cyan-100 lg:col-span-2">{selected?JSON.stringify({...selected,readiness:readiness(selected),launchUrl:launchUrl(selected),externalActionCompleted:false},null,2):"Select a mission to view its receipt."}</pre></section>
 </section></main>
}
