import { NextResponse } from "next/server";

import { missionStates, serviceRegistry } from "@/lib/service-bridge";

export function GET() {
  const generatedAt = new Date().toISOString();
  const services = serviceRegistry.map((service) => ({
    id: service.id,
    name: service.name,
    kind: service.kind,
    capabilityCount: service.capabilities.length,
    externalAction: service.externalAction,
  }));

  return NextResponse.json({
    receiptType: "JP / Hviti Service Bridge System Receipt",
    version: 17,
    generatedAt,
    system: {
      application: "/service-bridge",
      nexus: "/service-bridge/nexus",
      operatorConsole: "/service-bridge/control",
      statusConsole: "/service-bridge/status",
      lifecycleConsole: "/service-bridge/lifecycle",
      lifecycleProjectionConsole: "/service-bridge/lifecycle-project",
      lifecycleApplyConsole: "/service-bridge/lifecycle-apply",
      deploymentConsole: "/service-bridge/deployment",
      missionStateCount: missionStates.length,
      serviceCount: serviceRegistry.length,
      services,
    },
    boundaries: {
      explicitApprovalRequired: true,
      automaticMutationAllowed: false,
      automaticRollbackAllowed: false,
      explicitProjectionMutationAllowed: true,
      automaticProjectionMutationAllowed: false,
      automaticDeploymentAllowed: false,
      localPersistenceAllowed: true,
      localRollbackAllowed: true,
      externalPersistenceAllowed: false,
      externalRollbackAllowed: false,
      providerAuthorizationRequired: true,
      independentPublicUrlVerificationRequired: true,
      publicDeploymentVerifiedByReceipt: false,
      externalActionCompletedByReceipt: false,
      controlledActions: [
        "purchases",
        "bookings",
        "orders",
        "applications",
        "payments",
        "submissions",
        "messages",
        "calendar changes",
        "provider deployment",
        "domain changes",
      ],
    },
    lifecycle: {
      journal: {
        schema: "jp-hviti-service-bridge-lifecycle-entry/v1",
        digestAlgorithm: "SHA-256",
        canonicalization: "sorted-json-v1",
        missionScoped: true,
        tamperDetection: true,
      },
      projection: {
        schema: "jp-hviti-service-bridge-lifecycle-projection/v1",
        readOnly: true,
        invalidJournalStatus: 422,
      },
      apply: {
        schema: "jp-hviti-service-bridge-lifecycle-projection-apply-plan/v1",
        planningConfirmationPattern: "APPLY PROJECTION <mission-id>",
        commitConfirmationPattern: "COMMIT PROJECTION <mission-id>",
        mutationAppliedByApi: false,
      },
      limitations: {
        trustedTimestamp: false,
        signed: false,
        notarized: false,
        blockchain: false,
        identityProof: false,
        legalAuthorityProof: false,
        externalActionProof: false,
      },
    },
    deploymentBridge: {
      readinessSchema: "jp-hviti-service-bridge-deployment-readiness/v1",
      repairPlanSchema: "jp-hviti-service-bridge-deployment-repair-plan/v1",
      publicVerificationSchema: "jp-hviti-service-bridge-public-deployment-verification/v1",
      repairConfirmationPattern: "PLAN DEPLOYMENT REPAIR <commit-sha>",
      supportedStrategies: [
        "repair-vercel-account",
        "repair-vercel-project",
        "bridge-to-netlify",
        "bridge-to-other-provider",
        "verify-existing-deployment",
      ],
      netlifyConfiguration: "netlify.toml",
      automaticDeploymentAllowed: false,
      deploymentCompleted: false,
      publicDeploymentVerified: false,
      externalActionCompleted: false,
    },
    endpoints: {
      manifest: "/api/service-bridge/manifest",
      health: "/api/service-bridge/health",
      openapi: "/api/service-bridge/openapi",
      validate: "/api/service-bridge/validate",
      validateBatch: "/api/service-bridge/validate-batch",
      policyEvaluate: "/api/service-bridge/policy/evaluate",
      orchestrate: "/api/service-bridge/orchestrate",
      orchestrateBatch: "/api/service-bridge/orchestrate-batch",
      plan: "/api/service-bridge/plan",
      queue: "/api/service-bridge/queue",
      receipt: "/api/service-bridge/receipt",
      missionReceipt: "/api/service-bridge/receipt/mission",
      verifyReceipt: "/api/service-bridge/receipt/verify",
      appendEvent: "/api/service-bridge/events/append",
      verifyEventChain: "/api/service-bridge/events/verify",
      projectEventChain: "/api/service-bridge/events/project",
      reconcileSnapshot: "/api/service-bridge/events/reconcile",
      resolveAuthority: "/api/service-bridge/events/resolve",
      planPersistence: "/api/service-bridge/events/persist",
      planRollback: "/api/service-bridge/events/rollback",
      lifecycleJournal: "/api/service-bridge/lifecycle",
      lifecycleProject: "/api/service-bridge/lifecycle/project",
      lifecycleApply: "/api/service-bridge/lifecycle/apply",
      deploymentReadiness: "/api/service-bridge/deployment",
      deploymentRepair: "/api/service-bridge/deployment/repair",
    },
    verification: {
      architectureContractCommand: "npm run service-bridge:check",
      runtimeContractCommand: "npm run service-bridge:check:runtime",
      ciContractCommand: "npm run service-bridge:check:ci",
      combinedContractCommand: "npm run service-bridge:check:all",
      releaseCommand: "npm run service-bridge:verify",
      unifiedSmokeCommand: "npm run service-bridge:smoke:all",
      deploymentSmokeCommand: "npm run service-bridge:smoke:deployment",
      publicDeploymentVerificationCommand: "npm run service-bridge:deployment:verify -- <https-url>",
      workflow: ".github/workflows/service-bridge-verify.yml",
      contractExpected: "PASS",
      productionBuildExpected: "PASS",
      smokeSuiteCountExpected: 8,
    },
    externalActionCompleted: false,
  });
}
