import { NextResponse } from "next/server";

import { missionStates, serviceRegistry } from "@/lib/service-bridge";

export function GET() {
  return NextResponse.json({
    system: "JP / Hviti Service Bridge",
    version: 13,
    mode: "local-first-with-orchestration-integrity-recovery-resolution-and-gated-persistence",
    missionStates,
    services: serviceRegistry,
    limits: {
      batchValidationMaximum: 100,
      batchOrchestrationMaximum: 100,
      queueAnalysisMaximum: 250,
    },
    approvalLaw: {
      externalActionsRequireExplicitApproval: true,
      externalActionCompletedByManifest: false,
      policyDecisions: ["ALLOW_PREPARE", "HOLD_FOR_APPROVAL", "BLOCK"],
      controlledActions: ["purchases", "bookings", "orders", "applications", "payments", "submissions", "messages", "calendar changes"],
    },
    orchestration: {
      stages: ["validate", "policy", "route", "receipt", "next-action"],
      modes: ["single", "batch"],
      externalActionCompleted: false,
    },
    recovery: {
      stages: ["event-chain", "verify", "project", "reconcile", "resolve-authority", "plan-persistence", "explicit-local-write"],
      authorities: ["snapshot", "projection", "manual"],
      planningConfirmationPattern: "PERSIST <mission-id>",
      applyConfirmationPattern: "APPLY LOCAL <mission-id>",
      silentOverwriteAllowed: false,
      automaticMutationAllowed: false,
      localPersistenceOnly: true,
      externalActionCompleted: false,
    },
    endpoints: {
      manifest: "/api/service-bridge/manifest",
      health: "/api/service-bridge/health",
      openapi: "/api/service-bridge/openapi",
      validate: "/api/service-bridge/validate",
      validateBatch: "/api/service-bridge/validate-batch",
      policyEvaluate: "/api/service-bridge/policy/evaluate",
      orchestrate: "/api/service-bridge/orchestrate",
      orchestrateBatch: "/api/service-bridge/orchestrate-batch",
      plan: "/api/service-bridge/plan",
      queue: "/api/service-bridge/queue",
      receipt: "/api/service-bridge/receipt",
      missionReceipt: "/api/service-bridge/receipt/mission",
      verifyReceipt: "/api/service-bridge/receipt/verify",
      appendEvent: "/api/service-bridge/events/append",
      verifyEventChain: "/api/service-bridge/events/verify",
      projectEventChain: "/api/service-bridge/events/project",
      reconcileSnapshot: "/api/service-bridge/events/reconcile",
      resolveAuthority: "/api/service-bridge/events/resolve",
      planPersistence: "/api/service-bridge/events/persist",
      application: "/service-bridge",
      nexus: "/service-bridge/nexus",
      operatorConsole: "/service-bridge/control",
      policyConsole: "/service-bridge/policy",
      orchestrationConsole: "/service-bridge/orchestrate",
      batchOrchestrationConsole: "/service-bridge/orchestrate-batch",
      projectionConsole: "/service-bridge/projection",
      reconciliationConsole: "/service-bridge/reconcile",
      resolutionConsole: "/service-bridge/resolve",
      persistenceConsole: "/service-bridge/persist",
      statusConsole: "/service-bridge/status",
      receiptConsole: "/service-bridge/receipts",
      eventConsole: "/service-bridge/events",
    },
    examples: { sampleMissionQueue: "/examples/service-bridge/sample-missions.json" },
  });
}
