import { NextResponse } from "next/server";

import { missionStates, serviceRegistry } from "@/lib/service-bridge";

export function GET() {
  return NextResponse.json({
    system: "JP / Hviti Service Bridge",
    version: 17,
    mode: "local-first-with-orchestration-integrity-recovery-reversible-persistence-chained-lifecycle-projection-explicit-apply-and-deployment-repair",
    missionStates,
    services: serviceRegistry,
    limits: {
      batchValidationMaximum: 100,
      batchOrchestrationMaximum: 100,
      queueAnalysisMaximum: 250,
    },
    approvalLaw: {
      externalActionsRequireExplicitApproval: true,
      externalActionCompletedByManifest: false,
      policyDecisions: ["ALLOW_PREPARE", "HOLD_FOR_APPROVAL", "BLOCK"],
      controlledActions: ["purchases", "bookings", "orders", "applications", "payments", "submissions", "messages", "calendar changes", "provider deployment", "domain changes"],
    },
    orchestration: {
      stages: ["validate", "policy", "route", "receipt", "next-action"],
      modes: ["single", "batch"],
      externalActionCompleted: false,
    },
    recovery: {
      stages: ["event-chain", "verify", "project", "reconcile", "resolve-authority", "plan-persistence", "explicit-local-write", "plan-rollback", "explicit-local-restore", "append-lifecycle-entry", "verify-lifecycle-journal", "project-lifecycle", "plan-projection-apply", "explicit-projection-commit", "assess-deployment", "plan-deployment-repair", "verify-public-deployment"],
      authorities: ["snapshot", "projection", "manual"],
      planningConfirmationPattern: "PERSIST <mission-id>",
      applyConfirmationPattern: "APPLY LOCAL <mission-id>",
      rollbackPlanningConfirmationPattern: "ROLLBACK LOCAL <mission-id>",
      rollbackApplyConfirmationPattern: "APPLY ROLLBACK <mission-id>",
      projectionPlanningConfirmationPattern: "APPLY PROJECTION <mission-id>",
      projectionCommitConfirmationPattern: "COMMIT PROJECTION <mission-id>",
      deploymentRepairConfirmationPattern: "PLAN DEPLOYMENT REPAIR <commit-sha>",
      silentOverwriteAllowed: false,
      automaticMutationAllowed: false,
      automaticRollbackAllowed: false,
      automaticProjectionMutationAllowed: false,
      automaticDeploymentAllowed: false,
      explicitProjectionMutationAllowed: true,
      localPersistenceOnly: true,
      localRollbackOnly: true,
      externalActionCompleted: false,
    },
    lifecycleJournal: {
      schema: "jp-hviti-service-bridge-lifecycle-entry/v1",
      entryTypes: ["RESOLUTION_CREATED", "PERSISTENCE_PLANNED", "LOCAL_PERSISTENCE_APPLIED", "ROLLBACK_PLANNED", "LOCAL_ROLLBACK_APPLIED"],
      digestAlgorithm: "SHA-256",
      canonicalization: "sorted-json-v1",
      missionScoped: true,
      orderedByPreviousDigest: true,
      tamperDetection: true,
      trustedTimestamp: false,
      signed: false,
      notarized: false,
      blockchain: false,
      externalActionProof: false,
      externalActionCompleted: false,
    },
    lifecycleProjection: {
      schema: "jp-hviti-service-bridge-lifecycle-projection/v1",
      readOnlyProjection: true,
      derivesPersistedState: true,
      derivesRollbackState: true,
      detectsUnresolvedPlans: true,
      invalidJournalStatus: 422,
      externalActionCompleted: false,
    },
    lifecycleProjectionApply: {
      schema: "jp-hviti-service-bridge-lifecycle-projection-apply-plan/v1",
      localMutationAllowed: true,
      automaticMutationAllowed: false,
      planningConfirmationPattern: "APPLY PROJECTION <mission-id>",
      commitConfirmationPattern: "COMMIT PROJECTION <mission-id>",
      externalPersistenceAllowed: false,
      externalActionCompleted: false,
    },
    deploymentBridge: {
      readinessSchema: "jp-hviti-service-bridge-deployment-readiness/v1",
      repairPlanSchema: "jp-hviti-service-bridge-deployment-repair-plan/v1",
      publicVerificationSchema: "jp-hviti-service-bridge-public-deployment-verification/v1",
      repairConfirmationPattern: "PLAN DEPLOYMENT REPAIR <commit-sha>",
      supportedStrategies: ["repair-vercel-account", "repair-vercel-project", "bridge-to-netlify", "bridge-to-other-provider", "verify-existing-deployment"],
      automaticDeploymentAllowed: false,
      providerAuthorizationRequired: true,
      independentPublicUrlVerificationRequired: true,
      publicDeploymentVerifiedByManifest: false,
      externalActionCompleted: false,
    },
    endpoints: {
      manifest: "/api/service-bridge/manifest",
      health: "/api/service-bridge/health",
      openapi: "/api/service-bridge/openapi",
      validate: "/api/service-bridge/validate",
      validateBatch: "/api/service-bridge/validate-batch",
      policyEvaluate: "/api/service-bridge/policy/evaluate",
      orchestrate: "/api/service-bridge/orchestrate",
      orchestrateBatch: "/api/service-bridge/orchestrate-batch",
      plan: "/api/service-bridge/plan",
      queue: "/api/service-bridge/queue",
      receipt: "/api/service-bridge/receipt",
      missionReceipt: "/api/service-bridge/receipt/mission",
      verifyReceipt: "/api/service-bridge/receipt/verify",
      appendEvent: "/api/service-bridge/events/append",
      verifyEventChain: "/api/service-bridge/events/verify",
      projectEventChain: "/api/service-bridge/events/project",
      reconcileSnapshot: "/api/service-bridge/events/reconcile",
      resolveAuthority: "/api/service-bridge/events/resolve",
      planPersistence: "/api/service-bridge/events/persist",
      planRollback: "/api/service-bridge/events/rollback",
      lifecycleJournal: "/api/service-bridge/lifecycle",
      lifecycleProject: "/api/service-bridge/lifecycle/project",
      lifecycleApply: "/api/service-bridge/lifecycle/apply",
      deploymentReadiness: "/api/service-bridge/deployment",
      deploymentRepair: "/api/service-bridge/deployment/repair",
      application: "/service-bridge",
      nexus: "/service-bridge/nexus",
      operatorConsole: "/service-bridge/control",
      policyConsole: "/service-bridge/policy",
      orchestrationConsole: "/service-bridge/orchestrate",
      batchOrchestrationConsole: "/service-bridge/orchestrate-batch",
      projectionConsole: "/service-bridge/projection",
      reconciliationConsole: "/service-bridge/reconcile",
      resolutionConsole: "/service-bridge/resolve",
      persistenceConsole: "/service-bridge/persist",
      rollbackConsole: "/service-bridge/rollback",
      lifecycleConsole: "/service-bridge/lifecycle",
      lifecycleProjectionConsole: "/service-bridge/lifecycle-project",
      lifecycleApplyConsole: "/service-bridge/lifecycle-apply",
      deploymentConsole: "/service-bridge/deployment",
      statusConsole: "/service-bridge/status",
      receiptConsole: "/service-bridge/receipts",
      eventConsole: "/service-bridge/events",
    },
    examples: { sampleMissionQueue: "/examples/service-bridge/sample-missions.json" },
  });
}
